query Summary($term: String!) {
  areaSummary(term: $term) {
    term
    place_of_interest_summaries {
      category
      total
      tops {
        name
      }
    }
    photos {
      url
      place_name
      place_id
    }
  }
}
